name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: dotnet build src/dotnet-veml7700.sln -c Release
