name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish src/WebApp/WebApp.csproj --configuration Release --output bin --no-build