name: Release

on:
 release:
   types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build
      run: dotnet build --configuration Release
    
    - name: Publish
      run: dotnet publish src/WebApp/WebApp.csproj -c Release -r linux-arm64 --output bin

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: bin/

  package:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build

    steps:
    - name: Download binaries
      uses: actions/download-artifact@v2
      with:
        name: binaries
        path: pkg/usr/bin/dotnet-veml7700

    - name: Build package
      uses: jiro4989/build-deb-action@v2
      with:
        package: dotnet-veml7700
        package_root: pkg
        maintainer: github.com/jeff-winn
        version: ${{ github.ref }}
        desc: |
          ASP.NET Core Web API for an Adafruit VEML7700 light sensor.
        arch: arm64
        depends: aspnetcore-runtime-5.0

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: ./dotnet-veml7700*.deb
